/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContentId = IDL.Text;
export const Content = IDL.Record({ 'title' : IDL.Text, 'body' : IDL.Text });

export const idlService = IDL.Service({
  'createContent' : IDL.Func([ContentId, IDL.Text, IDL.Text], [], []),
  'deleteContent' : IDL.Func([ContentId], [], []),
  'getAllContents' : IDL.Func([], [IDL.Vec(Content)], ['query']),
  'getContent' : IDL.Func([ContentId], [Content], ['query']),
  'updateContent' : IDL.Func([ContentId, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContentId = IDL.Text;
  const Content = IDL.Record({ 'title' : IDL.Text, 'body' : IDL.Text });
  
  return IDL.Service({
    'createContent' : IDL.Func([ContentId, IDL.Text, IDL.Text], [], []),
    'deleteContent' : IDL.Func([ContentId], [], []),
    'getAllContents' : IDL.Func([], [IDL.Vec(Content)], ['query']),
    'getContent' : IDL.Func([ContentId], [Content], ['query']),
    'updateContent' : IDL.Func([ContentId, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };